# Generated by Django 4.2.7 on 2023-12-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='usser',
            new_name='user',
        ),
    ]
